"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { FileText, Shield, Mail, Phone, MapPin } from "lucide-react";

export default function HIPAAPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative py-24 overflow-hidden bg-primary">
        <div className="container relative z-10">
          <motion.div
            className="max-w-3xl"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="flex items-center gap-3 mb-4">
              <Shield className="h-8 w-8 text-primary-foreground" />
              <h1 className="font-display text-4xl md:text-5xl font-bold text-primary-foreground">
                HIPAA Notice of Privacy Practices
              </h1>
            </div>
            <p className="text-xl text-primary-foreground/90 leading-relaxed">
              Effective Date: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
            <p className="text-lg text-primary-foreground/80 mt-4 font-medium">
              THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content */}
      <section className="py-20">
        <div className="container max-w-4xl">
          <div className="prose prose-lg max-w-none space-y-12">
            
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-4">Who Will Follow This Notice</h2>
              <p className="text-muted-foreground leading-relaxed">
                This Notice of Privacy Practices describes Pain Atlanta's practices and those of our employees, 
                staff, volunteers, and other personnel who are involved in your care. Pain Atlanta and these 
                individuals will follow the terms of this Notice, and may use or disclose medical information 
                about you to carry out treatment, payment or health care operations, or for other purposes 
                as permitted or required by law. This Notice describes your rights to access and control 
                medical information about you, including information that may identify you and that relates 
                to your past, present, or future physical, medical, or mental condition and medical care 
                and related health care services.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-4">Our Pledge Regarding Medical Information</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Pain Atlanta understands that medical information about you and your health is personal. 
                We are committed to protecting medical information about you. In order to provide you with 
                quality care and to comply with certain state and federal legal requirements, we create a 
                record of the services you receive at our practice. This Notice applies to all of the records 
                of your care generated by Pain Atlanta.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                Pain Atlanta is required by law to: (1) Make sure that medical information that identifies 
                you is kept private; (2) Give you this Notice of its legal duties and privacy practices 
                concerning medical information about you; (3) Follow the terms of the Notice that are 
                currently in effect, and (4) Notify you in case there is an unauthorized use or disclosure 
                of your unsecured medical information.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-4">How We May Use and Disclose Medical Information About You</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                The following categories describe different ways that we may use or disclose protected 
                medical information. For each category of uses and disclosures, we will explain what is 
                meant and may give some examples. Not every use or disclosure in a category will be listed. 
                However, all of the ways we are permitted to use and disclose information will fall within 
                one of the categories.
              </p>

              <div className="space-y-6 mt-6">
                <div>
                  <h3 className="font-semibold text-foreground mb-2">For Treatment</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We may use medical information about you to provide you with medical treatment or services. 
                    We may disclose medical information about you to doctors, nurses, technicians, or other 
                    personnel who are involved in taking care of you.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">For Payment</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We may use and disclose medical information about you so that we can get paid for the 
                    treatment and services you receive at our practice. This may include billing your 
                    insurance company, a third-party payer, or you directly.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">For Health Care Operations</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We may use and disclose medical information about you to carry out activities that are 
                    necessary for our operations. These uses or disclosures are made for quality of care, 
                    compliance activities, administrative purposes, contractual obligations, grievances or 
                    lawsuits. For example, we may use medical information to review treatment and services 
                    provided at our practice or to evaluate the performance of our staff and contractors 
                    in caring for you.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">To Individuals or Family Members Involved in Your Health Care</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    Unless you object, we may disclose medical information about you to a member of your 
                    family, a relative, close friend or any other person that you identify who is involved 
                    in your care. We may also tell your family or friends, personal representative, or any 
                    other person who is responsible for your care, of your location, general condition or 
                    death, unless you object.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">As Required By Law</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We will disclose your health information when required to do so by federal, state or local law.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Workers' Compensation</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We may release medical information about you for workers' compensation or similar programs. 
                    These programs provide benefits for work-related injuries or illness.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">For Public Health Activities</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We may disclose medical information about you for public health activities. These purposes 
                    generally include: (1) To prevent or control disease, injury, or disability; (2) To report 
                    deaths; (3) To report abuse or neglect; (4) To report reactions to medications or problems 
                    with products; (5) To notify people of recalls of products they may be using; and (6) To 
                    notify a person who may have been exposed to a disease or who may be at risk for contracting 
                    or spreading a disease or condition.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">For Lawsuits and Disputes</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We may disclose medical information about you in response to a court or administrative order, 
                    subpoena, discovery request, or other lawful process.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Marketing</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We will not release your medical information for marketing purposes without an authorization from you.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Sale of Medical Information</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    We will not sell your medical information without an authorization from you.
                  </p>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="bg-sage-light/30 rounded-2xl p-8 border border-border"
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-6">Your Rights</h2>
              <p className="text-muted-foreground leading-relaxed mb-6">
                You have the following rights regarding your medical information. In order to exercise these 
                rights, you must contact Pain Atlanta's Privacy Officer. You may be asked to submit a written request.
              </p>

              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-foreground mb-2">Right to Inspect and Copy</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    With certain exceptions, you have the right to inspect and receive copies of your medical information.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Amendment</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    If you feel that medical information about you is incorrect or incomplete, you may ask 
                    us to amend the information.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Right to an Accounting of Disclosures</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    You have the right to receive a list of certain disclosures that we may have made of 
                    your medical information.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Right to Request Restrictions</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    You have the right to request a restriction or limitation on medical information that 
                    we use or disclose about you for treatment, payment or health care operations, and to 
                    request a limit on the medical information that we may disclose to family members or 
                    friends involved in your care.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Request Confidential Communications</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    You have the right to request that we communicate with you about your appointments or 
                    other matters related to your treatment in a specific way or at a specific location.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold text-foreground mb-2">Receive a Copy</h3>
                  <p className="text-muted-foreground leading-relaxed">
                    You have the right to obtain a copy of this notice.
                  </p>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.4 }}
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-4">Questions and Complaints</h2>
              <p className="text-muted-foreground leading-relaxed mb-6">
                If you have any questions or believe that your privacy rights have been violated, you may 
                contact Pain Atlanta's Privacy Officer:
              </p>
              
              <div className="bg-card rounded-xl p-6 border border-border/50 space-y-3">
                <div className="flex items-start gap-3">
                  <MapPin className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="font-semibold text-foreground">Pain Atlanta</p>
                    <p className="text-muted-foreground">Attn: Privacy Officer</p>
                    <p className="text-muted-foreground">2045 Rockbridge Road</p>
                    <p className="text-muted-foreground">Stone Mountain, GA 30087</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Phone className="h-5 w-5 text-primary flex-shrink-0" />
                  <a href="tel:+17704697330" className="text-primary hover:underline">(770) 469-7330</a>
                </div>
                <div className="flex items-center gap-3">
                  <Mail className="h-5 w-5 text-primary flex-shrink-0" />
                  <a href="mailto:info@painatlanta.com" className="text-primary hover:underline">info@painatlanta.com</a>
                </div>
              </div>

              <p className="text-muted-foreground leading-relaxed mt-6">
                You may also file a written complaint with the Department of Health and Human Services at:
              </p>
              
              <div className="bg-card rounded-xl p-6 border border-border/50 mt-4">
                <p className="font-semibold text-foreground mb-2">Centralized Case Management Operations</p>
                <p className="text-muted-foreground">U.S. Department of Health and Human Services</p>
                <p className="text-muted-foreground">200 Independence Avenue, S.W.</p>
                <p className="text-muted-foreground">Room 509F HHH Bldg.</p>
                <p className="text-muted-foreground">Washington, D.C. 20201</p>
                <p className="text-muted-foreground mt-2">
                  Toll-free: <a href="tel:+18003681019" className="text-primary hover:underline">(800) 368-1019</a>
                </p>
                <p className="text-muted-foreground">
                  TDD toll-free: <a href="tel:+18005377697" className="text-primary hover:underline">(800) 537-7697</a>
                </p>
              </div>

              <p className="text-muted-foreground leading-relaxed mt-4 font-medium">
                You will not be penalized or retaliated against for filing a complaint.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.5 }}
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-4">Changes to This Notice</h2>
              <p className="text-muted-foreground leading-relaxed">
                Pain Atlanta reserves the right to change the terms of this Notice at any time. We reserve 
                the right to make the revised or changed notice effective for medical information we already 
                have about you as well as any information we receive in the future. We will post a copy of 
                the current Notice. The Notice will contain an effective date.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.6 }}
              className="pt-8 border-t border-border"
            >
              <h2 className="font-display text-2xl font-bold text-foreground mb-4">Other Uses of Medical Information</h2>
              <p className="text-muted-foreground leading-relaxed">
                Other uses and disclosures of medical information not covered by this Notice or the laws that 
                apply to use will be made only with your written permission. If you provide us permission to 
                use or disclose medical information about you, you may revoke that permission in writing at any 
                time. If you revoke your permission we will stop any further use or disclosure of your medical 
                information for the purposes covered by your written authorization, except if we have already 
                acted in reliance on your permission. You understand that we are unable to take back any 
                disclosure we have already made with your permission and that we are required to retain our 
                records of the care that we provided to you.
              </p>
            </motion.div>
          </div>
        </div>
      </section>
    </>
  );
}

